# Generated by Django 3.2.5 on 2021-08-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
