# Generated by Django 3.2.5 on 2021-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomps',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
