# Generated by Django 3.2.5 on 2021-08-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomp', '0002_pomps_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomps',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
